# 1. Initialize Temperature and Humidity Data

In [2]:
import numpy as np
np.random.seed(0)
temperature_data = np.random.uniform(-10, 40, (500, 365))
humidity_data = np.random.uniform(0, 100, (500, 365))


# 2. Check for Missing Data

In [3]:
mask = np.random.choice([True, False], size=temperature_data.shape, p=[0.05, 0.95])
temperature_data[mask] = np.nan
humidity_data[mask] = np.nan

missing_temperature = np.isnan(temperature_data).sum()
missing_humidity = np.isnan(humidity_data).sum()

print("Total missing entries in temperature_data:", missing_temperature)
print("Total missing entries in humidity_data:", missing_humidity)


Total missing entries in temperature_data: 9088
Total missing entries in humidity_data: 9088


# 3. Convert Temperature and Calculate Discomfort Index

In [4]:
temperature_data_fahrenheit = temperature_data * 9/5 + 32
discomfort_index = temperature_data + 0.55 * (1 - humidity_data / 100) * (temperature_data - 58)
discomfort_index = np.clip(discomfort_index, None, 80)


# 4. Analyze January Temperatures

In [5]:
january_data = temperature_data[:, :31]
january_avg_temp = np.nanmean(january_data)
print("Average January temperature across all locations:", january_avg_temp)


Average January temperature across all locations: 15.057905709791807


# 5. Identify Extreme Temperatures

In [6]:
temperature_data[temperature_data > 35] = np.nan
null_per_location = np.isnan(temperature_data).sum(axis=1)
print("Number of null values per location due to extreme temperatures:", null_per_location)


Number of null values per location due to extreme temperatures: [52 61 51 61 54 53 57 55 56 51 41 52 44 42 52 53 43 50 53 45 56 49 43 52
 54 53 66 60 45 49 55 53 57 48 43 61 41 45 56 51 60 62 51 43 57 58 49 57
 62 47 64 56 57 46 58 68 47 73 60 47 52 61 65 52 43 63 35 56 46 49 43 63
 58 53 41 50 49 61 43 59 66 58 44 55 63 57 50 45 46 55 43 50 49 46 45 51
 53 57 55 54 57 46 53 59 52 63 60 50 57 56 55 55 50 49 59 48 49 53 57 55
 60 48 53 44 56 56 54 48 52 49 47 45 52 51 49 48 52 62 54 64 53 58 38 52
 48 56 56 33 46 54 45 62 45 51 49 51 55 48 43 55 50 60 64 48 58 52 48 62
 41 53 36 63 53 58 46 53 49 50 45 41 68 51 49 55 60 50 56 64 52 56 51 52
 58 58 40 47 55 52 55 64 59 61 42 56 46 54 60 52 66 46 52 57 53 42 64 52
 58 58 55 49 52 64 50 54 61 53 50 49 45 39 45 53 46 61 50 62 58 60 49 51
 51 47 50 59 59 69 49 52 48 44 48 63 61 41 56 51 47 64 60 58 56 52 43 60
 54 49 47 52 59 60 53 53 50 53 51 53 63 64 50 63 48 48 65 54 58 55 71 51
 44 59 51 44 63 46 60 43 51 59 50 48 57 53 49 47 52 54 47 64

# 6. Calculate Quarterly Temperature Averages

In [7]:
quarterly_data = temperature_data[:, :364].reshape(500, 4, 91)
quarterly_avg = np.nanmean(quarterly_data, axis=2)
print("Quarterly average temperatures for each location:\n", quarterly_avg)


Quarterly average temperatures for each location:
 [[11.31817555 14.44633514 11.66169602 10.35317935]
 [10.6039256  12.7002658  12.33682497 12.41836172]
 [11.8103234  13.29927529 12.44403298 11.3246437 ]
 ...
 [ 9.74635001 11.64427784 14.36179697 12.99081444]
 [11.81290054 12.73674978 14.89180279 13.18451207]
 [12.08930199 14.2550813  14.32264695 14.84522726]]


# 7. Classify Humidity Levels

In [8]:
dry_days = (humidity_data < 30).sum(axis=1)
humid_days = (humidity_data > 70).sum(axis=1)

print("Number of 'Dry' days per location:", dry_days)
print("Number of 'Humid' days per location:", humid_days)


Number of 'Dry' days per location: [ 96 112 105 105  93 123 102 104  97 102  93  99  86 126 106  93 100 107
 112 127 115  97 116 106  98 110  89  98 106 111 119  99  99  79 116 104
 106  98 115 106  95 109 103  98 103  92 111 106  98 107  89 107  88  95
 105 112 106 113  92 133  91 102  98 116  93 118 115 119 105  96  97 117
 110 110 102 108  99 121 112 110  92 107  93  97 104 105 101  96 122 110
 118 109 112 111 111 104 105  98 101 117  96 100 113 100 113 106 121 111
 101  94 100 109  94  92 111  91 113  94 111 116 107 122 110 109  94 111
  94 109 100 118 102 101 106 115  90 121 104 101 107 105 106  97 108 117
 105 110  94  97  93 107  99 105 113  98  92 124 100 105 101 105 101 103
  89 102  98 102 102 110  98 109 100 106 112 102 123 103  99 106  93 109
 108 106 113 109 111 108 103  98 101 104  93 110 102  92 109 113 115 104
 106 104 110 111 103 112  97 116  96 114 114 100 100 108  99 113 109 101
  94 106 106 113  99 102 116 103 116 104 113  88 110 110 107  97 101 110
 106  95 112 104

# 8. Apply Daily Pressure Trend to Temperature Data

In [9]:
pressure_trend = 1 + 0.1 * np.sin(np.linspace(0, 2 * np.pi, 365))
temperature_adjusted = temperature_data * pressure_trend
print("Sample of adjusted temperature data:", temperature_adjusted[:5, :5])


Sample of adjusted temperature data: [[17.4406752  25.80393081 20.20767799 17.33341725 11.25989097]
 [12.93019809 26.25361918  9.98561401         nan 24.67028794]
 [15.05315864  8.83468071  8.2740524   3.06098747 14.90061142]
 [27.94922774 -9.16276395         nan 20.86032086 17.74352882]
 [        nan         nan 12.98079501 31.03246426 28.64864573]]
